name: "Build and Deploy to GitHub Pages"

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: "4.2.1"

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    container:
      image: barichello/godot-ci:4.2.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.2.1.stable
          mv /root/.local/share/godot/export_templates/4.2.1.stable/* ~/.local/share/godot/export_templates/4.2.1.stable

      - name: Web Build
        run: |
          mkdir -p build/web
          godot --headless --verbose --export-release "Web" ./build/web/index.html

      - name: Add COOP/COEP Service Worker
        run: |
          curl -o build/web/coi-serviceworker.js https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.js

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
