name: Deploy Godot Game with Github Pages

on:
  push:
    branches: [main]

jobs:
  export_html5:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    env:
      GODOT_PROJECT_PATH: .
      EXPORT_PRESETS: "HTML5"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Export HTML5 Build
        run: godot-ci export

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: html5-build
          path: build
